package com.mdsword.hello.spring.boot.mybatis.dao;

import com.mdsword.hello.spring.boot.mybatis.entity.StWxTransferRecord;
import java.util.List;

public interface StWxTransferRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ST_WX_TRANSFER_RECORD
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ST_WX_TRANSFER_RECORD
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    int insert(StWxTransferRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ST_WX_TRANSFER_RECORD
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    StWxTransferRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ST_WX_TRANSFER_RECORD
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    List<StWxTransferRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ST_WX_TRANSFER_RECORD
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    int updateByPrimaryKey(StWxTransferRecord record);
}