package com.mdsword.hello.spring.boot.mybatis.dao;

import com.mdsword.hello.spring.boot.mybatis.entity.Table2;
import java.util.List;

public interface Table2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE2
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    int insert(Table2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE2
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    List<Table2> selectAll();
}