package com.mdsword.hello.spring.boot.mybatis.dao;

import com.mdsword.hello.spring.boot.mybatis.entity.Table1;
import java.util.List;

public interface Table1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    int insert(Table1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    List<Table1> selectAll();
}