package com.mdsword.hello.spring.boot.mybatis.dao;

import com.mdsword.hello.spring.boot.mybatis.entity.TMenu;
import java.util.List;

public interface TMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    int insert(TMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    TMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    List<TMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    int updateByPrimaryKey(TMenu record);
}