package com.mdsword.hello.spring.boot.mybatis.dao;

import com.mdsword.hello.spring.boot.mybatis.entity.TRoleMenu;
import java.util.List;

public interface TRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    int insert(TRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    TRoleMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    List<TRoleMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    int updateByPrimaryKey(TRoleMenu record);
}