package com.mdsword.hello.spring.boot.mybatis.entity;

import java.util.Date;

public class StWxTransferRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_TRANSFER_RECORD.ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_TRANSFER_RECORD.STORE_ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_TRANSFER_RECORD.ORDER_ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_TRANSFER_RECORD.OPEN_ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_TRANSFER_RECORD.RECEIVER_NAME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_TRANSFER_RECORD.MONEY
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_TRANSFER_RECORD.STATUS
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_TRANSFER_RECORD.CREATOR
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_TRANSFER_RECORD.CREATE_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_TRANSFER_RECORD.MODIFIER
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_TRANSFER_RECORD.MODIFY_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_TRANSFER_RECORD.STR_TAG
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String strTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_TRANSFER_RECORD.INT_TAG
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer intTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_TRANSFER_RECORD.ID
     *
     * @return the value of ST_WX_TRANSFER_RECORD.ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_TRANSFER_RECORD.ID
     *
     * @param id the value for ST_WX_TRANSFER_RECORD.ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_TRANSFER_RECORD.STORE_ID
     *
     * @return the value of ST_WX_TRANSFER_RECORD.STORE_ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_TRANSFER_RECORD.STORE_ID
     *
     * @param storeId the value for ST_WX_TRANSFER_RECORD.STORE_ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_TRANSFER_RECORD.ORDER_ID
     *
     * @return the value of ST_WX_TRANSFER_RECORD.ORDER_ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_TRANSFER_RECORD.ORDER_ID
     *
     * @param orderId the value for ST_WX_TRANSFER_RECORD.ORDER_ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_TRANSFER_RECORD.OPEN_ID
     *
     * @return the value of ST_WX_TRANSFER_RECORD.OPEN_ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_TRANSFER_RECORD.OPEN_ID
     *
     * @param openId the value for ST_WX_TRANSFER_RECORD.OPEN_ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_TRANSFER_RECORD.RECEIVER_NAME
     *
     * @return the value of ST_WX_TRANSFER_RECORD.RECEIVER_NAME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_TRANSFER_RECORD.RECEIVER_NAME
     *
     * @param receiverName the value for ST_WX_TRANSFER_RECORD.RECEIVER_NAME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_TRANSFER_RECORD.MONEY
     *
     * @return the value of ST_WX_TRANSFER_RECORD.MONEY
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_TRANSFER_RECORD.MONEY
     *
     * @param money the value for ST_WX_TRANSFER_RECORD.MONEY
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_TRANSFER_RECORD.STATUS
     *
     * @return the value of ST_WX_TRANSFER_RECORD.STATUS
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_TRANSFER_RECORD.STATUS
     *
     * @param status the value for ST_WX_TRANSFER_RECORD.STATUS
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_TRANSFER_RECORD.CREATOR
     *
     * @return the value of ST_WX_TRANSFER_RECORD.CREATOR
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_TRANSFER_RECORD.CREATOR
     *
     * @param creator the value for ST_WX_TRANSFER_RECORD.CREATOR
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_TRANSFER_RECORD.CREATE_TIME
     *
     * @return the value of ST_WX_TRANSFER_RECORD.CREATE_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_TRANSFER_RECORD.CREATE_TIME
     *
     * @param createTime the value for ST_WX_TRANSFER_RECORD.CREATE_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_TRANSFER_RECORD.MODIFIER
     *
     * @return the value of ST_WX_TRANSFER_RECORD.MODIFIER
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_TRANSFER_RECORD.MODIFIER
     *
     * @param modifier the value for ST_WX_TRANSFER_RECORD.MODIFIER
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_TRANSFER_RECORD.MODIFY_TIME
     *
     * @return the value of ST_WX_TRANSFER_RECORD.MODIFY_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_TRANSFER_RECORD.MODIFY_TIME
     *
     * @param modifyTime the value for ST_WX_TRANSFER_RECORD.MODIFY_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_TRANSFER_RECORD.STR_TAG
     *
     * @return the value of ST_WX_TRANSFER_RECORD.STR_TAG
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getStrTag() {
        return strTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_TRANSFER_RECORD.STR_TAG
     *
     * @param strTag the value for ST_WX_TRANSFER_RECORD.STR_TAG
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setStrTag(String strTag) {
        this.strTag = strTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_TRANSFER_RECORD.INT_TAG
     *
     * @return the value of ST_WX_TRANSFER_RECORD.INT_TAG
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getIntTag() {
        return intTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_TRANSFER_RECORD.INT_TAG
     *
     * @param intTag the value for ST_WX_TRANSFER_RECORD.INT_TAG
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setIntTag(Integer intTag) {
        this.intTag = intTag;
    }
}