package com.mdsword.hello.spring.boot.mybatis.entity;

import java.util.Date;

public class StWxBill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.ORDER_ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.ORDER_NO
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.TYPE
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.AMOUNT_ACTUAL
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer amountActual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.AMOUNT
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.RATE
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.BALANCE_AMOUNT
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer balanceAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.INFO_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Long infoTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.DESCRIPTION
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.REMARK
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.CREATOR
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.CREATE_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.MODIFIER
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.MODIFY_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.STR_TAG
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String strTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.INT_TAG
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer intTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_WX_BILL.CASH_ACCOUNT_WX
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String cashAccountWx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.ID
     *
     * @return the value of ST_WX_BILL.ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.ID
     *
     * @param id the value for ST_WX_BILL.ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.ORDER_ID
     *
     * @return the value of ST_WX_BILL.ORDER_ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.ORDER_ID
     *
     * @param orderId the value for ST_WX_BILL.ORDER_ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.ORDER_NO
     *
     * @return the value of ST_WX_BILL.ORDER_NO
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.ORDER_NO
     *
     * @param orderNo the value for ST_WX_BILL.ORDER_NO
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.TYPE
     *
     * @return the value of ST_WX_BILL.TYPE
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.TYPE
     *
     * @param type the value for ST_WX_BILL.TYPE
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.AMOUNT_ACTUAL
     *
     * @return the value of ST_WX_BILL.AMOUNT_ACTUAL
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getAmountActual() {
        return amountActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.AMOUNT_ACTUAL
     *
     * @param amountActual the value for ST_WX_BILL.AMOUNT_ACTUAL
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setAmountActual(Integer amountActual) {
        this.amountActual = amountActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.AMOUNT
     *
     * @return the value of ST_WX_BILL.AMOUNT
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.AMOUNT
     *
     * @param amount the value for ST_WX_BILL.AMOUNT
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.RATE
     *
     * @return the value of ST_WX_BILL.RATE
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.RATE
     *
     * @param rate the value for ST_WX_BILL.RATE
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setRate(Integer rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.BALANCE_AMOUNT
     *
     * @return the value of ST_WX_BILL.BALANCE_AMOUNT
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getBalanceAmount() {
        return balanceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.BALANCE_AMOUNT
     *
     * @param balanceAmount the value for ST_WX_BILL.BALANCE_AMOUNT
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setBalanceAmount(Integer balanceAmount) {
        this.balanceAmount = balanceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.INFO_TIME
     *
     * @return the value of ST_WX_BILL.INFO_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Long getInfoTime() {
        return infoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.INFO_TIME
     *
     * @param infoTime the value for ST_WX_BILL.INFO_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setInfoTime(Long infoTime) {
        this.infoTime = infoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.DESCRIPTION
     *
     * @return the value of ST_WX_BILL.DESCRIPTION
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.DESCRIPTION
     *
     * @param description the value for ST_WX_BILL.DESCRIPTION
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.REMARK
     *
     * @return the value of ST_WX_BILL.REMARK
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.REMARK
     *
     * @param remark the value for ST_WX_BILL.REMARK
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.CREATOR
     *
     * @return the value of ST_WX_BILL.CREATOR
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.CREATOR
     *
     * @param creator the value for ST_WX_BILL.CREATOR
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.CREATE_TIME
     *
     * @return the value of ST_WX_BILL.CREATE_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.CREATE_TIME
     *
     * @param createTime the value for ST_WX_BILL.CREATE_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.MODIFIER
     *
     * @return the value of ST_WX_BILL.MODIFIER
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.MODIFIER
     *
     * @param modifier the value for ST_WX_BILL.MODIFIER
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.MODIFY_TIME
     *
     * @return the value of ST_WX_BILL.MODIFY_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.MODIFY_TIME
     *
     * @param modifyTime the value for ST_WX_BILL.MODIFY_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.STR_TAG
     *
     * @return the value of ST_WX_BILL.STR_TAG
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getStrTag() {
        return strTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.STR_TAG
     *
     * @param strTag the value for ST_WX_BILL.STR_TAG
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setStrTag(String strTag) {
        this.strTag = strTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.INT_TAG
     *
     * @return the value of ST_WX_BILL.INT_TAG
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getIntTag() {
        return intTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.INT_TAG
     *
     * @param intTag the value for ST_WX_BILL.INT_TAG
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setIntTag(Integer intTag) {
        this.intTag = intTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_WX_BILL.CASH_ACCOUNT_WX
     *
     * @return the value of ST_WX_BILL.CASH_ACCOUNT_WX
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getCashAccountWx() {
        return cashAccountWx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_WX_BILL.CASH_ACCOUNT_WX
     *
     * @param cashAccountWx the value for ST_WX_BILL.CASH_ACCOUNT_WX
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setCashAccountWx(String cashAccountWx) {
        this.cashAccountWx = cashAccountWx;
    }
}