package com.mdsword.hello.spring.boot.mybatis.entity;

import java.util.Date;

public class Table2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE2.ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE2.ID_CARD
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE2.JULY_CARD_NO
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String julyCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE2.IS_SCAN_ALIPAY_CARD
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String isScanAlipayCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE2.SCAN_ALIPAY_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Date scanAlipayTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE2.ID
     *
     * @return the value of TABLE2.ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE2.ID
     *
     * @param id the value for TABLE2.ID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE2.ID_CARD
     *
     * @return the value of TABLE2.ID_CARD
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE2.ID_CARD
     *
     * @param idCard the value for TABLE2.ID_CARD
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE2.JULY_CARD_NO
     *
     * @return the value of TABLE2.JULY_CARD_NO
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getJulyCardNo() {
        return julyCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE2.JULY_CARD_NO
     *
     * @param julyCardNo the value for TABLE2.JULY_CARD_NO
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setJulyCardNo(String julyCardNo) {
        this.julyCardNo = julyCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE2.IS_SCAN_ALIPAY_CARD
     *
     * @return the value of TABLE2.IS_SCAN_ALIPAY_CARD
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getIsScanAlipayCard() {
        return isScanAlipayCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE2.IS_SCAN_ALIPAY_CARD
     *
     * @param isScanAlipayCard the value for TABLE2.IS_SCAN_ALIPAY_CARD
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setIsScanAlipayCard(String isScanAlipayCard) {
        this.isScanAlipayCard = isScanAlipayCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE2.SCAN_ALIPAY_TIME
     *
     * @return the value of TABLE2.SCAN_ALIPAY_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Date getScanAlipayTime() {
        return scanAlipayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE2.SCAN_ALIPAY_TIME
     *
     * @param scanAlipayTime the value for TABLE2.SCAN_ALIPAY_TIME
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setScanAlipayTime(Date scanAlipayTime) {
        this.scanAlipayTime = scanAlipayTime;
    }
}