package com.mdsword.hello.spring.boot.mybatis.entity;

import java.util.Date;

public class Table1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE1.CREATETM
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Date createtm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE1.UNIQUEID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String uniqueid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE1.CERTIFICATEID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String certificateid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE1.CREATETM
     *
     * @return the value of TABLE1.CREATETM
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Date getCreatetm() {
        return createtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE1.CREATETM
     *
     * @param createtm the value for TABLE1.CREATETM
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setCreatetm(Date createtm) {
        this.createtm = createtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE1.UNIQUEID
     *
     * @return the value of TABLE1.UNIQUEID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getUniqueid() {
        return uniqueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE1.UNIQUEID
     *
     * @param uniqueid the value for TABLE1.UNIQUEID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setUniqueid(String uniqueid) {
        this.uniqueid = uniqueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE1.CERTIFICATEID
     *
     * @return the value of TABLE1.CERTIFICATEID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getCertificateid() {
        return certificateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE1.CERTIFICATEID
     *
     * @param certificateid the value for TABLE1.CERTIFICATEID
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setCertificateid(String certificateid) {
        this.certificateid = certificateid;
    }
}