package com.mdsword.hello.spring.boot.mybatis.entity;

public class Table3 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE3.id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE3.name
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE3.id
     *
     * @return the value of TABLE3.id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE3.id
     *
     * @param id the value for TABLE3.id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE3.name
     *
     * @return the value of TABLE3.name
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE3.name
     *
     * @param name the value for TABLE3.name
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}