package com.mdsword.hello.spring.boot.mybatis.entity;

public class TMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.icon
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.name
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.state
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.url
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.p_id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer pId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.id
     *
     * @return the value of t_menu.id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.id
     *
     * @param id the value for t_menu.id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.icon
     *
     * @return the value of t_menu.icon
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.icon
     *
     * @param icon the value for t_menu.icon
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.name
     *
     * @return the value of t_menu.name
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.name
     *
     * @param name the value for t_menu.name
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.state
     *
     * @return the value of t_menu.state
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.state
     *
     * @param state the value for t_menu.state
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.url
     *
     * @return the value of t_menu.url
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.url
     *
     * @param url the value for t_menu.url
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.p_id
     *
     * @return the value of t_menu.p_id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.p_id
     *
     * @param pId the value for t_menu.p_id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }
}