package com.mdsword.hello.spring.boot.mybatis.entity;

public class TRoleMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_menu.id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_menu.menu_id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_menu.role_id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_menu.id
     *
     * @return the value of t_role_menu.id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_menu.id
     *
     * @param id the value for t_role_menu.id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_menu.menu_id
     *
     * @return the value of t_role_menu.menu_id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_menu.menu_id
     *
     * @param menuId the value for t_role_menu.menu_id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_menu.role_id
     *
     * @return the value of t_role_menu.role_id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_menu.role_id
     *
     * @param roleId the value for t_role_menu.role_id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}