package com.mdsword.hello.spring.boot.mybatis.entity;

public class TUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.bz
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String bz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.true_name
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String trueName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_name
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.remarks
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.bz
     *
     * @return the value of t_user.bz
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.bz
     *
     * @param bz the value for t_user.bz
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setBz(String bz) {
        this.bz = bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.true_name
     *
     * @return the value of t_user.true_name
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.true_name
     *
     * @param trueName the value for t_user.true_name
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_name
     *
     * @return the value of t_user.user_name
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_name
     *
     * @param userName the value for t_user.user_name
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.remarks
     *
     * @return the value of t_user.remarks
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.remarks
     *
     * @param remarks the value for t_user.remarks
     *
     * @mbg.generated Tue Feb 19 10:46:17 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}